[package]
name = "Proyecto2"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies]
raylib = "5.5.1"
image = "0.25"
rayon = "1.11.0"
